version: '3.8'

services:
  bank-message-tokenizer:
    build: .
    container_name: financial-ner
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx2g -Xms1g
      - LOG_LEVEL=INFO
      - MODEL_PATH=/app/models
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - financial-network

  # Optional: Redis for caching results
  redis-cache:
    image: redis:7-alpine
    container_name: financial-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - financial-network

volumes:
  redis-data:

networks:
  financial-network:
    driver: bridge
